app/Main.hs, fourmolu.cabal, fourmolu.yaml, src/Ormolu.hs, src/Ormolu/Config.hs, src/Ormolu/Printer.hs, src/Ormolu/Printer/Internal.hs
Closes #2.
Fourmolu looks through parent directories, then [the XDG config directory](https://hackage.haskell.org/package/directory-1.3.6.1/docs/System-Directory.html#v:XdgConfig), for a `fourmolu.yaml`, which is used to override config fields. Right now, the only field is `indentation`.
So a config file just looks like:
```yaml
indentation: 4
```
=> Add support for config files

data/examples/declaration/value/function/infix/do-out.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
The more I've thought about this, it seems that the behaviour causing the remaining test failure at #1 is really very specific to that sort of expression (a `do` block in the LHS of an infix operator). And frankly I'd be suspicious of code that looked like that anyway - before today I wouldn't have been confident at a glance of how that parses.
So I figure it's better to treat it as the unusual edge case it is. #5 seems overkill, since, as one fix led to another, the changes became more pervasive than we'd want, in terms of behaviour and LOC. This patch gets straight to the point, and is thus much smaller in both senses.
=> Stop operators from being indented past `do`.

README.md, app/Main.hs, src/Ormolu.hs, src/Ormolu/Config.hs, src/Ormolu/Printer.hs, src/Ormolu/Printer/Internal.hs, tests/Ormolu/PrinterSpec.hs
This took me longer than I planned, but finally here's a working version that solves #12. In the end I decided to follow the approach proposed by @georgefst, but perhaps I've stopped a few steps earlier than it was intended.
I've had a number of decisions to make, and I'll try to explain myself.
* There's no short version of the `--indentation` option: I wanted to avoid conflicts with `ormolu` if they add an `-i` option in the future.
* I'm not sure if deriving `Eq` and `Show` for `PrinterOptsPartial` and `PrinterOptsTotal` is done the "right" way. I wanted to stay conservative. The  `StandaloneDeriving` extension seemed safer to me than `UndecidableInstances`, which could perhaps allow me to save a few lines (but I'm not even sure about that, I have not tried).
* I've not defined a HKD …
=> Add --indentation CLI option.

stack.yaml
As reported in #12, because of the `aeson-1.5.2.0` dependency, the project didn't build with using neither the `stack.yaml` file in the repo, nor the one described in the `README`. I am able to build it using the `stack.yaml` as in this PR. 
However, this boosts the required GHC version to 8.8.3. Probably `lts-15.3` (GHC 8.8.2) would also work. I'm not sure what the best practice is.
I didn't manage to build it using `stack` and GHC 8.6.5.
=> Fix `stack.yaml` (`aeson-1.5.2.0` dependency).

format.sh
I got burnt by the fact that it was using the globally installed `fourmolu`, rather than the current source...
This fix still isn't really ideal, as there can be a lot of recompilation before reaching a fixed point. What might be nicest is to wait until `cabal run` allows using the bytecode interpreter.
=> Fix formatting script

app/Main.hs, data/examples/module-header/leading-empty-line-four-out.hs, data/examples/module-header/named-section-four-out.hs, data/examples/other/comment-style-transform-four-out.hs, data/examples/other/comment-style-transform-out.hs, data/examples/other/following-comment-last-3-four-out.hs, data/examples/other/haddock-sections-four-out.hs, fourmolu.yaml, src/Ormolu/Config.hs, src/Ormolu/Parser/CommentStream.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Meat/Common.hs, src/Ormolu/Printer/Meat/ImportExport.hs, src/Ormolu/Utils.hs, tests/Ormolu/PrinterSpec.hs
My initial intention here was just to preserve haddock comments completely. But that seems to be difficult, since the GHC API doesn't actually tell us, for example, whether a comment used single-line (`--`) or multi-line (`{- -}`) style. We *could* use the `SrcSpan`s to grab the appropriate text from the input verbatim, but that's a bit nasty.
So, I've gone with @michaelpj's suggestion from [the Ormolu thread about this](https://github.com/tweag/ormolu/issues/641), which is to always print in multi-line style for multi-line haddocks, even if they originally just used multiple `--`s. One slight gotcha is that:
```hs
-- | Multi
-- line
-- comment
```
becomes:
```hs
{- | Multi
line
comment
-}
```
, when it might seem more natural for the leading spaces to be removed. And, depending on the …
=> Use multiline comment style for multiline haddocks

app/Main.hs
Otherwise this becomes the first line of output when in stdout mode.
An alternative would be to use stderr (perhaps only when in stdout mode), if it's important information is shown prominently.
=> Write loaded config info to stderr instead of stdout 

README.md, app/Main.hs, src/Ormolu/Config.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Internal.hs, src/Ormolu/Printer/Meat/Declaration.hs, src/Ormolu/Printer/Meat/Module.hs, src/Ormolu/Utils.hs, tests/Ormolu/PrinterSpec.hs
The number of newlines between declarations can now be configured with 'newlines-between-decls' configuration option.
Closes #47 
This does exactly what I want! It's idempotent as well. It defaults to exactly ormolu behavior. I tested it on our large industrial codebase. I don't see anything unexpected from my initial skim. If we merge this, I think we'd start using this at @bitnomial.
=> Configurable newlines between declarations

app/Main.hs, src/Ormolu/Config.hs
Closes #27.
This solves the problem described in #27. At the same time I wanted to reduce the number of places where the strings encoding option values were hardcoded, which resulted in rewriting/replacing `parseHaddockStyle`, `parseCommaStyle` and `parseBool` and modifying the way that the help texts are built.
I also decided to make the error messages a bit more user friendly by providing the user with the list of possible values of an option (because it was nearly free with the new approach).
Some comments:
1. I don't understand why booleans are case-insensitive and other options are case-sensitive. Do we really want it this way?
2. The values can still be represented in different ways on the command line and in the config file. I think it would be nice if we had a single source of …
=> Replace hardcoded defaults. Remove parser boilerplate. (#27)

app/Main.hs
This just applies the machinery of #44 to the new option `--newlines-between-decls` introduced in #48 (so that we use the default value of `poNewlinesBetweenDecls` from `defaultPrinterOpts` instead of hardcoding it in the help text).
=> Remove hardcoded default for poNewlinesBetweenDecls from help text.

fourmolu.cabal
As instructed in the README, ran `cabal test` and `./format.sh` and had no issues.
I would really appreciate if the hackage metadata could be updated after this is merged.
Thanks!
=> Relax aeson version lower bound requirement

fourmolu.cabal
Tested locally:
1. Add `path-0.8.0` to `extra-deps` in `stack.yaml`
2. Run `stack test`
=> Bump path upper bound

README.md, data/examples/other/disabling/mixed-styles-four-out.hs, data/examples/other/disabling/mixed-styles-out.hs, data/examples/other/disabling/mixed-styles.hs, src/Ormolu/Processing/Preprocess.hs
Closes #70. 
After looking at the code I've decided **not** to add another option, and **not** to track which of the comments was used to disable the formatter. I just treat the two styles of comments as equivalent (e.g. after using `{- ORMOLU_DISABLE -}` we may use `{- FOURMOLU_ENABLE -}` to re-enable formatting), but I do not change the style of the comment used in the original file.
Adding an extra option just for this seemed weird. It's easy, but it adds much noise.
Tracking could be useful in some scenarios, but do we really need this?
This solution is simple, keeps Ormolu compatibility and is consistent with the current behavior.
However, if you think it's wrong this way, feel free to close the PR.
=> do not revert Fourmolu magic comments to Ormolu form

data/examples/declaration/data/field-layout/record-four-out.hs, data/examples/declaration/data/record-four-out.hs, data/examples/declaration/data/record-multi-const-four-out.hs, src/Ormolu/Printer/Meat/Type.hs
This is inspired by (and lifts the core code from) #98.
Differences:
- It's rebased on to `master`.
- The comments are moved two spaces left. I think this looks better, but I'm happy to hear any dissenting opinions. This is the reason for the removal of the `sitcc` call in `Ormolu.Printer.Meat.Type`.
- There's no separate option. Instead we just follow `poCommaStyle`, and use trailing haddocks iff it's set to `Leading`. This removes the "Disallow this in combination with trailing comma style" concern (I'm not sure `optparse-applicative` provides a nice way to do that). And the old style is so ugly that I really don't see any reason why anyone would prefer it. It's just a relic of adapting Ormolu to leading commas in the simplest way possible.
=> Use trailing haddocks for record fields when using leading commas

.gitignore, fourmolu.cabal, stack-ghc-9.0.yaml
Fourmolu works with aeson 2 out of the box, so I already bumped the Hackage bounds for aeson 2: https://hackage.haskell.org/package/fourmolu-0.4.0.0/revisions/
=> Support aeson 2

fourmolu.cabal
Should have happened when we gave him permission. Just an oversight.
=> Add Brandon to maintainers list in Cabal file

.circleci/config.yml, cabal.project, stack-ghc-8.10.yaml, stack-ghc-9.0.yaml, stack-ghc-9.2.yaml
Carrying on the conversation from https://github.com/fourmolu/fourmolu/pull/129#issuecomment-981870050:
> I actually intentionally want `-Werror` on in local development. If it's gonna fail in CI, why not have it fail locally? `cabal.project` also has it nominally on (although it should be updated to `fourmolu +dev` instead of `ormolu +dev`), so I'd rather we change it so both Stack and Cabal have `-Werror` on in local development
I've never personally understood the desire to enable `-Werror`, other than when one wants to ensure that builds output a non-zero exit code in the presence of warnings, e.g. in CI. During interactive development, surely it's often useful to run code that contains potentially-harmless issues like unused variables, or missing type signatures? I feel like I must …
=> Avoid setting Ormolu dev flag in Cabal config

stack-ghc-9.2.yaml
https://app.circleci.com/pipelines/github/fourmolu/fourmolu/176/workflows/43180fe7-9782-424b-82c3-4d2a1f66b530/jobs/663
Fix failure, due to GHC 9.2.2 being released a week ago, we need to pin GHC 9.2.1 to match the version of ghc-lib-parser-9.2.1
=> Pin GHC 9.2.1

CHANGELOG.md, src/Ormolu/Printer/Meat/Type.hs
Partially revert https://github.com/fourmolu/fourmolu/pull/124 (specifically, the removal of `sitcc`) to fix https://github.com/fourmolu/fourmolu/issues/145
Completely separate from whether it looks better or not, that change actually causes inconsistencies with different options. Some examples are below. TL;DR we should revert this for now to fix the inconsistencies, then we can make the trailing comment indentation configurable for aesthetic reasons
With `--indentation=4`, `--comma-style=trailing` and `--comma-style=leading` will indent the two comments differently:
```console
$ stack exec -- fourmolu --indentation=4 --comma-style=trailing test.hs
newtype App a = App
{ unApp ::
JobExecutorT
( ReaderT
MyConfig
(LoggingT IO)
)
a,
-- | asfd
a :: Int,
-- | asdf
b :: Bool
}
$ stack exec -- …
```
=> Fix regression with multiline record types

CHANGELOG.md, src/Ormolu/Printer/Meat/Declaration/Data.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs
Fixes #142 
Ormolu refactored all this code after 0.4.0.0 was released, so this code will probably go away. But fixes the weirdness for now.
Ref. https://github.com/tweag/ormolu/pull/830
=> Fix indentation after list comprehension

CHANGELOG.md, app/Main.hs
Supercedes #101, fixes #110
Solves the immediate issue of suppressing the "Loaded config from: ..." output. Long-term, we should probably think about whether we want to consolidate `optQuiet` and `cfgDebug` into a single "log level" field (but keeping them separate cli flags); but maybe we want to keep ormolu-owned logging separate from fourmolu-owned logging?
=> Add --quiet flag

DEVELOPER.md, fourmolu.cabal, region-tests/Main.hs
The test suite doesn't import `fourmolu`, so it doesn't need it as a dependency. However, running tests does require the executable, so one needs to remember to explicitly build the executable. Keeping `fourmolu` as a dependency doesn't help with this; the dependency only specifies the library as a dependency, not the executable, and Stack will only build the executable the first time.
Also show better output if the command fails
=> Improve region tests

README.md, app/Main.hs, fourmolu.cabal, src/Ormolu/Config.hs, tests/Ormolu/CabalInfoSpec.hs
`yaml` is more standard + has better error messages than `HsYAML`:
```yaml
foo: 1
bar
```
```console
Failed to load /Users/brandino/repos/fourmolu/fourmolu.yaml:
Unexpected 'b'
```
```console
Failed to load /Users/brandino/repos/fourmolu/fourmolu.yaml:
YAML parse exception at line 2, column 0,
while scanning a simple key:
could not find expected ':'
```
Plus some clean up commits
=> Use better YAML library

scripts/make_release.py
Unfortunately, GitHub Actions will return an empty string if an expression fails, not an error.
=> Check hackage token

data/examples/import/nested-explicit-imports-four-ie-out.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Meat/ImportExport.hs
`commaDel'` now checks the import export lists comma option. This makes nested list imports being formatted similarly to regular lists.
fixes #174 
cc @brandonchinn178
=> Use import export comma option in commaDel'

src/Ormolu/Printer/Combinators.hs
Was wrongly positioned in #187. Also adds a missing comment.
cc @brandonchinn178
=> Fix `commaDelImportExport` export position.

app/Main.hs, fourmolu.cabal, src/Ormolu/Config.hs, src/Ormolu/Config/TH.hs, src/Ormolu/Config/Types.hs, src/Ormolu/Printer/Internal.hs
Resolves https://github.com/fourmolu/fourmolu/issues/50
Help text:
```diff
-  --indentation WIDTH      Number of spaces per indentation step (default '4')
-  --comma-style STYLE      How to place commas in multi-line lists, records etc:
-                           'leading' or 'trailing' (default 'leading')
+  --indentation WIDTH      Number of spaces per indentation step (default: 4)
+  --comma-style STYLE      How to place commas in multi-line lists, records,
+                           etc. (choices: "leading" or "trailing")
+                           (default: "leading")
--indent-wheres BOOL     Whether to indent 'where' bindings past the preceding
body (rather than half-indenting the 'where' keyword)
-                           (default 'false')
+                           (default: …
```
=> Add single source of truth for JSON/CLI configuration

CHANGELOG.md, data/fourmolu/haddock-style/input.hs, data/fourmolu/haddock-style/output-HaddockMultiLine.hs, data/fourmolu/haddock-style/output-HaddockSingleLine.hs, src/Ormolu/Printer/Meat/Common.hs
Fixes #172 and adds a test. Blocked on #169
@georgefst would be great to get #169 merged so that we can start merging PRs using the new test framework
=> Support consecutive newlines in multiline haddocks

.github/workflows/ci.yml
GitHub actions has limits on number of concurrent macos jobs, so we'll reduce our matrix for macos
=> Only run macos job on latest stack.yaml

.github/workflows/pr-review-comment.yml, DEVELOPER.md, changelog.d/README.md
This hopefully fixes the issue that every PR merged introduces a merge conflict in all open PRs. This also solves the issue where a release is made, but open PRs would add their CHANGELOG entry under the already-released section
=> Add changelog.d/ directory

README.md, changelog.d/multi-line-compact.md, data/fourmolu/haddock-style/output-HaddockMultiLineCompact.hs, src/Ormolu/Config.hs, src/Ormolu/Config/Types.hs, src/Ormolu/Printer/Meat/Common.hs
Blocked on #49?
Related to #74 
It always kinda bothered me when multiline haddocks were formatted like
```hs
{- |
Some multiline
comment here
-}
```
The haddock documentation always uses `{-|` without the space
=> Add option for spaceless '{-|'

CHANGELOG.md, DEVELOPER.md, README.md, changelog.d/function-arrows.md, changelog.d/multi-line-compact.md, fourmolu.cabal, fourmolu.yaml, src/Ormolu/Config.hs, src/Ormolu/Config/Types.hs, tests/Ormolu/Config/PrinterOptsSpec.hs
Ignore the branch name :)
Also includes doc changes. This is the first time we've included "curate the order of configuration options" in the release checklist, so this is a bit more churn than we should expect for future releases.
Rough reasoning for option order:
```yaml
indentation
function-arrows
comma-style
import-export-style
indent-wheres
record-brace-space
newlines-between-decls
haddock-style
respectful
fixities
```
=> Release 0.8.2.0

.github/workflows/ci.yml
Trying to repro this failure: https://hackage.haskell.org/package/fourmolu-0.8.1.0/reports/2.
UPDATE: Seems like it's due to outdated packages on the Hackage server: https://github.com/digital-asset/ghc-lib/issues/407.
I'll still merge this in as a normal "build + test with cabal" test, which we should probably have anyway. I also took the opportunity to break up `build_and_test` into distinct `stack_test`, `cabal_test`, and `os_test` jobs.
=> Add cabal test in CI

changelog.d/function-arrows-fixes.md, data/examples/declaration/data/gadt/multiline-four-out.hs, data/examples/declaration/data/gadt/multiline-out.hs, data/examples/declaration/data/gadt/multiple-declaration-four-out.hs, data/examples/declaration/data/gadt/multiple-declaration-out.hs, data/fourmolu/function-arrows/input.hs, data/fourmolu/function-arrows/output-LeadingArrows.hs, data/fourmolu/function-arrows/output-TrailingArrows.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Internal.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs, src/Ormolu/Printer/Meat/Declaration/Signature.hs, src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Printer/Meat/Type.hs
Found some edge cases for function arrows, and was able to simplify the code without the `PrevTypeCtx` machinery.
Some of the changes I made seem to still pass tests (e.g. moving things in/out of a `located` block). If we find a regression or issue later, we can fix it later with an added test
=> Fixes for function arrows

README.md, changelog.d/unicode.md, data/fourmolu/unicode-syntax/input.hs, data/fourmolu/unicode-syntax/output-UnicodeAlways.hs, data/fourmolu/unicode-syntax/output-UnicodeDetect.hs, data/fourmolu/unicode-syntax/output-UnicodeNever.hs, fourmolu.yaml, src/Ormolu/Config.hs, src/Ormolu/Config/Types.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Meat/Declaration/Class.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs, src/Ormolu/Printer/Meat/Declaration/Signature.hs, src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, src/Ormolu/Printer/Meat/Type.hs, tests/Ormolu/Config/PrinterOptsSpec.hs
Resolves #134 
Unicode looks delicious _(with an appropriate font)_, but there is no input method for it out of the box. Therefore, most people avoid it. Now we do not need an input method — it will input itself, solving the problem for good.
=> Add option to format with Unicode syntax.

README.md, changelog.d/haddock-style-module.md, data/fourmolu/haddock-style/output-HaddockMultiLine-module=HaddockMultiLine.hs, data/fourmolu/haddock-style/output-HaddockMultiLine-module=HaddockMultiLineCompact.hs, data/fourmolu/haddock-style/output-HaddockMultiLine-module=HaddockSingleLine.hs, data/fourmolu/haddock-style/output-HaddockMultiLineCompact-module=HaddockMultiLine.hs, data/fourmolu/haddock-style/output-HaddockMultiLineCompact-module=HaddockMultiLineCompact.hs, data/fourmolu/haddock-style/output-HaddockMultiLineCompact-module=HaddockSingleLine.hs, data/fourmolu/haddock-style/output-HaddockSingleLine-module=HaddockMultiLine.hs, data/fourmolu/haddock-style/output-HaddockSingleLine-module=HaddockMultiLineCompact.hs, data/fourmolu/haddock-style/output-HaddockSingleLine-module=HaddockSingleLine.hs, fourmolu.yaml, src/Ormolu/Config.hs, src/Ormolu/Config/Types.hs, src/Ormolu/Printer/Meat/Common.hs, src/Ormolu/Printer/Meat/Module.hs, tests/Ormolu/Config/PrinterOptsSpec.hs
Blocked on #49?
Resolves https://github.com/fourmolu/fourmolu/issues/74
Adds a `haddock-style-module` option that specifies the haddock style to use specifically for the module docstring (when not set, resolves to whatever `haddock-style` is — the current behavior)
Tested with this file:
```hs
{- |
Module: Foo
-}
module Foo where
-- | This is a
-- multi line
-- haddock
foo :: Int
foo = 42
```
and this command:
```console
$ stack exec -- fourmolu --haddock-style=single-line --haddock-style-module=multi-line Foo.hs
{- |
Module: Foo
-}
module Foo where
-- | This is a
-- multi line
-- haddock
foo :: Int
foo = 42
```
=> Add haddock-style-module configuration

changelog.d/single-line-space.md, data/examples/module-header/leading-empty-line-four-out.hs, data/examples/module-header/named-section-four-out.hs, data/examples/other/comment-spacing-four-out.hs, data/examples/other/comment-spacing-out.hs, data/examples/other/comment-style-transform-out.hs, data/examples/other/following-comment-last-3-four-out.hs, data/examples/other/haddock-sections-four-out.hs, data/fourmolu/haddock-style/output-HaddockMultiLine-module=HaddockMultiLine.hs, data/fourmolu/haddock-style/output-HaddockMultiLine-module=HaddockMultiLineCompact.hs, data/fourmolu/haddock-style/output-HaddockMultiLine-module=HaddockSingleLine.hs, data/fourmolu/haddock-style/output-HaddockMultiLine.hs, data/fourmolu/haddock-style/output-HaddockMultiLineCompact-module=HaddockMultiLine.hs, data/fourmolu/haddock-style/output-HaddockMultiLineCompact-module=HaddockMultiLineCompact.hs, data/fourmolu/haddock-style/output-HaddockMultiLineCompact-module=HaddockSingleLine.hs, data/fourmolu/haddock-style/output-HaddockMultiLineCompact.hs, data/fourmolu/haddock-style/output-HaddockSingleLine-module=HaddockMultiLine.hs, data/fourmolu/haddock-style/output-HaddockSingleLine-module=HaddockMultiLineCompact.hs, data/fourmolu/haddock-style/output-HaddockSingleLine-module=HaddockSingleLine.hs, data/fourmolu/haddock-style/output-HaddockSingleLine.hs, src/Ormolu/Printer/Meat/Common.hs, src/Ormolu/Utils.hs
Fixes https://github.com/fourmolu/fourmolu/issues/212
=> Add space after '--' in single-line comments

README.md
Changed my mind as soon as I hit merge on https://github.com/fourmolu/fourmolu/pull/263.
Credit to @clintonmead.
=> Add version of `git ls-files` command which avoids length limits

README.md, changelog.d/single-context-parens.md, config/ConfigData.hs, data/fourmolu/single-context-parens/input.hs, data/fourmolu/single-context-parens/output-ConstraintAlways.hs, data/fourmolu/single-context-parens/output-ConstraintAuto.hs, data/fourmolu/single-context-parens/output-ConstraintNever.hs, fourmolu.yaml, src/Ormolu/Config/Gen.hs, src/Ormolu/Parser.hs, tests/Ormolu/Config/PrinterOptsSpec.hs
This option controls parenthesis around constraints in type signatures when there is only one:
```
function1 :: C a => a
function2 :: (C a) => a
```
becomes
```
-- Always (default)
function1 :: (C a) => a
function1 :: (C a) => a
-- Never
function1 :: C a => a
function2 :: C a => a
-- Auto
function1 :: C a => a
function2 :: (C a) => a
```
This addresses #288. Note that always is the default, even though the issue suggests auto (ignore) be the default. I did this because Ormolu always adds parenthesis, and it would break some other tests.
=> Add a single-context-parens option (#288)

web/README.md, web/fourmolu-wasm/Dockerfile, web/fourmolu-wasm/build.sh, web/fourmolu-wasm/cbits/init.c, web/fourmolu-wasm/fourmolu-wasm.cabal, web/fourmolu-wasm/src/Main.hs, web/site/static/hackage-info.bin, web/worker/index.js
The new ormolu merge [changed](https://github.com/tweag/ormolu/pull/991) how the fixity database is loaded (preinitialized with wizer instead of fetched at runtime). If you use any infix operators at fourmolu.github.io, it'll show an error.
@georgefst I can't compile this right now because `rts_clearMemory` was added [2 months ago](https://gitlab.haskell.org/ghc/ghc/-/commit/9ca51f9e84abc41ba590203d8bc8df8d6af86db2) while my build of GHC wasm is too old, and I'm getting a weird error about `tzset` being undeclared when rebuilding GHC. I'll try to get it working on my end, but if you can get it working, feel free to test/fix/merge.
=> Fix fourmolu demo for new ormolu

fourmolu.cabal
`ansi-terminal-1.0` is released on Hackage.
See also https://github.com/commercialhaskell/stackage/issues/6976.
Tested by building with Stack >= 2.9.3 and `stack-ghc-9.2.yaml` with additions:
~~~yaml
extra-deps:
- ansi-terminal-1.0
- ansi-terminal-types-0.11.5
allow-newer: true
allow-newer-deps:
- ansi-wl-pprint
~~~
=> Relax upper bound to accommodate ansi-terminal-1.0

.pre-commit-config.yaml, DEVELOPER.md, fourmolu.cabal, hie.yaml, tests/Ormolu/Integration/CLIOptionsSpec.hs, tests/Ormolu/Integration/FixitySpec.hs, tests/Ormolu/Integration/RegionSpec.hs, tests/Ormolu/Integration/Utils.hs
There's no reason to implement `fixity-tests` and `region-tests` in separate test suites, so I consolidated all the integration tests into `tests/Ormolu/Integration/`
=> Consolidate integration tests

fourmolu.cabal
Tested with
```bash
cabal test --constraint='deepseq==1.5.0.0' --allow-newer=deepseq --allow-boot-library-installs
```
Already pushed a revision to Hackage for 0.13.1.0
=> Bump deepseq bounds

changelog.d/column-limit-block-args.md, data/fourmolu/column-limit/input-multi.hs, data/fourmolu/column-limit/input.hs, data/fourmolu/column-limit/output-limit=100.hs, data/fourmolu/column-limit/output-limit=80.hs, data/fourmolu/column-limit/output-limit=none.hs, src/Ormolu/Printer/Combinators.hs, src/Ormolu/Printer/Meat/Declaration/Value.hs, tests/Ormolu/Config/PrinterOptsSpec.hs
Fixed #377 
There are also other similar places, e.g.
* https://github.com/fourmolu/fourmolu/blob/7a2d6dde1a9bb77ec3efc1a20c6199c194386a5d/src/Ormolu/Printer/Meat/Declaration/Value.hs#L322-L324
* https://github.com/fourmolu/fourmolu/blob/7a2d6dde1a9bb77ec3efc1a20c6199c194386a5d/src/Ormolu/Printer/Meat/Declaration/Value.hs#L432-L434
* https://github.com/fourmolu/fourmolu/blob/7a2d6dde1a9bb77ec3efc1a20c6199c194386a5d/src/Ormolu/Printer/Meat/Declaration/Value.hs#L587-L590
But I'm not sure how to fix this more generally. Leaving those unfixed for now
=> Fix column-limit with BlockArguments

.github/workflows/format-compat.yml, changelog.d/reexport-leading-export.md, compat-tests/cabal.diff, data/fourmolu/import-export/input-multi.hs, data/fourmolu/import-export/output-ImportExportDiffFriendly.hs, data/fourmolu/import-export/output-ImportExportLeading.hs, data/fourmolu/import-export/output-ImportExportTrailing.hs, src/Ormolu/Printer/Meat/ImportExport.hs
Resolves https://github.com/fourmolu/fourmolu/issues/381
The immediate cause of the breakage was #344 adding a fix for the first export with only haddocks preceding. But the logic was actually correct; the incorrect behavior was that module re-exports were re-indented as docstrings:
https://github.com/fourmolu/fourmolu/blob/7a2d6dde1a9bb77ec3efc1a20c6199c194386a5d/src/Ormolu/Printer/Meat/ImportExport.hs#L103
This seems to have been an oversight in https://github.com/fourmolu/fourmolu/pull/108.
So with the fix in #344, module re-exports were indented twice in the specific case where:
1. commaStyle = Leading
2. relativePos is not SinglePos or FirstPos
3. isAllPrevDoc is True
=> Fix first module re-export with section heading

app/Main.hs, changelog.d/fix-resolve-order.md, src/Ormolu/Config.hs, tests/Ormolu/ConfigSpec.hs
Fixes #390
The documentation of `resolvePrinterOpts` states that "later options override earlier", but it is not the case. This commit fixes the application order such that it is inline with the documentation.
=> Fix the order in which the configurations are applied

changelog.d/single-deriving-parens.md, config/FourmoluConfig/ConfigData.hs, data/fourmolu/single-deriving-parens/input.hs, data/fourmolu/single-deriving-parens/output-DerivingAlways.hs, data/fourmolu/single-deriving-parens/output-DerivingAuto.hs, data/fourmolu/single-deriving-parens/output-DerivingNever.hs, fourmolu.yaml, src/Ormolu/Config.hs, src/Ormolu/Config/Gen.hs, src/Ormolu/Diff/ParseResult.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs, tests/Ormolu/Config/PrinterOptsSpec.hs, web/site/pages/config/single-deriving-parens.md
As discussed in #385.
---
[33c7a8c](https://github.com/fourmolu/fourmolu/pull/386/commits/33c7a8c575772ff9d5288c69292e973fc7f2a3b4)
The current implementation of this function relies on the fact that we
never output un-parenthesised deriving classes from formatting. This
means the right-hand argument is never a `DctSingle`. If it ever were,
the function would incorrectly return a `Difference` no matter what,
even if it were the exact same `DctSingle` as the left-hand argument.
Since we're about to start making those parenthesis conditional, this
won't work. Instead, we now use `considerEqualVia` and pattern match on
a comparison of single-to-singleton or singleton-to-single. I find this
a conceptually simpler approach anyway, and is more lenient in the way
we need. …
=> Implement single-deriving-parens

fourmolu.cabal
Motivation: this is blocking the reintroduction of `ansi-terminal-1.1.x` to nightly snapshots. See: https://github.com/commercialhaskell/stackage/pull/7420#issuecomment-2110842180
=> Relax upper bound to admit ansi-terminal-1.1.1

.pre-commit-config.yaml, web/site/pages/config/comma-style.md, web/site/pages/config/import-export-style.md
Even if Ormolu has bad newlines, the merge conflicts shouldn't be that bad. Let's just fix them
=> Fix end-of-file newlines

.github/workflows/pr-review-comment.yml, README.md
While Fourmolu remains configurable, certain changes may still be breaking, e.g. if Ormolu makes a breaking change, or if no one would use the old format if not for old Fourmolu behavior. Generally, people should always be pinning a Fourmolu version in a project, but sometimes upgrades are required, e.g. when upgrading a project to use a newer GHC version. Simply upgrading a codebase to use a newer GHC can be a difficult task (e.g. https://github.com/haskell/core-libraries-committee/issues/12#issuecomment-971794515), so it can be frustrating when you realize you also have to reformat the codebase because upgrading to a version of Fourmolu that supports the new GHC version includes breaking changes. Somewhat relevant discussions: https://github.com/fourmolu/fourmolu/issues/363, …
=> RFC: Add policy for breaking changes

changelog.d/indent.md, compat-tests/cabal.diff, compat-tests/swarm.diff, data/examples/declaration/splice/bracket-declaration-out.hs, data/examples/declaration/splice/untyped-splice-out.hs, data/examples/declaration/value/function/infix/esqueleto-1-out.hs, data/examples/declaration/value/function/let-multi-line-out.hs, data/examples/declaration/value/function/operators-6-out.hs, data/examples/declaration/value/function/pattern/famous-cardano-pattern-out.hs, data/examples/declaration/value/function/pattern/splice-pattern-out.hs, data/examples/declaration/value/function/required-type-arguments-out.hs, src/Ormolu/Printer/Comments.hs, src/Ormolu/Printer/Internal.hs
We have logic in `inci` to round down to the closest multiple of the indentation before increasing the indentation, in the case of parenthesized expressions, which shift the indentation off the indentation column.
```hs
-- Ormolu behavior:
( Maybe
Int -> -- <- 'Int' is one indentation (2 spaces) from the column 'Maybe' starts on
String
)
-- If Fourmolu just naively changed indentation to 4:
( Maybe
Int -> -- <- 'Int' is one indentation (4 spaces) from the column 'Maybe' starts on,
String     -- but it now starts on column 6, because of the "( ", so all subsequent
)            -- newlines will be off the indentation column
-- Fourmolu's behavior today, rounding down (indentation=4):
( Maybe
Int -> -- <- The start of 'Maybe' is on column 2, so we round down to a multiple
String   -- of 4 …
```
=> Only apply indentation hack for indentation > 2

changelog.d/sort-constraints.md, config/FourmoluConfig/ConfigData.hs, data/fourmolu/sort-constraints/input.hs, data/fourmolu/sort-constraints/output-False.hs, data/fourmolu/sort-constraints/output-True.hs, fourmolu.yaml, src/Ormolu/Config/Gen.hs, src/Ormolu/Diff/ParseResult.hs, src/Ormolu/Printer/Meat/Type.hs, tests/Ormolu/Config/PrinterOptsSpec.hs, web/site/pages/config/sort-constraints.md
This adds some simple sorting of constraints. There are a few potential deficiencies:
1. It doesn't sort nested constraint tuples. We could solve this by carrying around some information about whether we are in a constraint context in `p_hsType`, but that seeemed moderately disruptive.
2. It doesn't handle constraint tuple synonyms. I think this is unavoidable since we can't know they're constraint tuples without type information.
3. The sorting is very crude, just sorting on the `Outputable` representation of  the type. I think this will more-or-less doe what people expect, but perhaps it's too expensive?
Fixes #247
=> Sort constraints in contexts

web/fourmolu-wasm/cbits/init.c
Fix error in WASM build:
```
cbits/init.c:12:5: error:
error: call to undeclared library function 'memset' with type 'void *(void *, int, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
12 |     memset(start, 0, (size_t)end - (size_t)start);
|     ^
|
12 |     memset(start, 0, (size_t)end - (size_t)start);
|     ^
cbits/init.c:12:5: error:
note: include the header <string.h> or explicitly provide a declaration for 'memset'
|
12 |     memset(start, 0, (size_t)end - (size_t)start);
|     ^
1 error generated.
`wasm32-wasi-clang' failed in phase `C Compiler'. (Exit code: 1)
Error: [Cabal-7125]
Failed to build exe:fourmolu-wasm from fourmolu-wasm-0.
```
Ormolu doesn't seem to do anything special to handle this, so I suspect …
=> Fix wasm build

web/site/cabal.project
https://discourse.haskell.org/t/debug-why-cabal-is-choosing-a-version/10547
=> Fix web build-plan

changelog.d/sort-derived-classes.md, changelog.d/sort-deriving-clauses.md, config/FourmoluConfig/ConfigData.hs, data/fourmolu/sort-derived-classes/input.hs, data/fourmolu/sort-derived-classes/output-False.hs, data/fourmolu/sort-derived-classes/output-True.hs, data/fourmolu/sort-deriving-clauses/input.hs, data/fourmolu/sort-deriving-clauses/output-False.hs, data/fourmolu/sort-deriving-clauses/output-True.hs, fourmolu.yaml, src/Ormolu/Config/Gen.hs, src/Ormolu/Diff/ParseResult.hs, src/Ormolu/Printer/Meat/Declaration/Data.hs, tests/Ormolu/Config/PrinterOptsSpec.hs, web/site/pages/config/sort-derived-classes.md, web/site/pages/config/sort-deriving-clauses.md
This adds two configuration options for sorting a) types in deriving clauses, and b) deriving clauses themselves.
Fixes https://github.com/tweag/ormolu/issues/968
=> Add configuration options for sorting deriving clauses and types

.github/workflows/ci.yml, .github/workflows/web.yml, CHANGELOG.md, changelog.d/implicit-params-parens.md, changelog.d/import-grouping.md, changelog.d/indent.md, changelog.d/multiline-comments-indented.md, changelog.d/sort-constraints.md, changelog.d/sort-derived-classes.md, changelog.d/sort-deriving-clauses.md, changelog.d/trailing-section-operators.md, config/FourmoluConfig/ConfigData.hs, fourmolu.cabal, fourmolu.yaml, src/Ormolu/Config/Gen.hs, tests/Ormolu/Config/PrinterOptsSpec.hs, web/README.md, web/fourmolu-wasm/cabal.project, web/fourmolu-wasm/cbits/init.c, web/site/fourmolu-web.cabal, web/site/pages/config/sort-constraints.md, web/site/pages/config/sort-derived-classes.md, web/site/pages/config/sort-deriving-clauses.md, web/site/pages/config/trailing-section-operators.md, web/site/site.hs, web/site/static/style.css
TODO:
* WASM was 7.42 MB before this change (https://github.com/fourmolu/fourmolu/actions/runs/12236298554)
* WASM is now 7.45 MB, which isn't a big regression ✅
=> Release 0.17.0.0
