stack.yaml

Fix HsYAML-aeson revision to use compatible aeson

---

CHANGELOG.md
fourmolu.cabal

Seeing as we've finally reached the point where I'm running Fourmolu on my own projects, and [people are itching to start using the new features](https://github.com/haskell/haskell-language-server/pull/445), seems the time for a release is upon us.
@parsonsmatt Last chance to cast an eye over recent changes, if you're still interested.

Release 0.2

---

data/examples/declaration/class/newlines-and-haddocks-four-out.hs
data/examples/declaration/class/newlines-and-haddocks-out.hs
data/examples/declaration/class/newlines-and-haddocks.hs
data/examples/module-header/multiline-with-comments-four-out.hs
data/examples/module-header/multiline-with-comments-out.hs
data/examples/module-header/multiline-with-comments.hs
src/Ormolu/Printer/Meat/Common.hs

Fixes https://github.com/parsonsmatt/fourmolu/issues/63 
Fixes https://github.com/parsonsmatt/fourmolu/issues/53

Fix multiline haddocks in indented contexts

---

data/examples/declaration/value/function/application-2-four-out.hs
data/examples/declaration/value/function/application-2-out.hs
data/examples/declaration/value/function/application-2.hs
src/Ormolu/Printer/Combinators.hs
src/Ormolu/Printer/Internal.hs
src/Ormolu/Printer/Meat/Declaration/Value.hs
src/Ormolu/Printer/Meat/ImportExport.hs

Resolves https://github.com/fourmolu/fourmolu/issues/114

Fix same line do block

---

CHANGELOG.md
fourmolu.cabal

Release 0.4

---

DEVELOPER.md
README.md
fourmolu.yaml

All other than 329363f59de18cd75b6d6b6b46f4c5be511b6954 are documentation improvements.

Miscellaneous small improvements, mostly documentation

---

DEVELOPER.md

Add release notes to DEVELOPER.md

---

src/Ormolu/Config/TH.hs

Constructors should not be provided multiple times when building a `BijectiveMap` using `mkBijectiveMap`
cc @brandonchinn178

Check for constructor duplicates in `mkBijectiveMap`

---

CHANGELOG.md
fourmolu.cabal

Release 0.8

---

CHANGELOG.md
src/Ormolu/Config.hs

This is useful for HLS: https://github.com/haskell/haskell-language-server/pull/3078

Add emptyConfig

---

CHANGELOG.md
app/Main.hs
fixity-tests/Main.hs
fourmolu.cabal
region-tests/Main.hs
tests/Ormolu/CabalInfoSpec.hs
tests/Ormolu/Config/OptionsSpec.hs
tests/utils/IntegrationUtils.hs

Resolves https://github.com/fourmolu/fourmolu/issues/224
Fixes breakage in #150

Fix CLI options not overriding config file

---

CHANGELOG.md
DEVELOPER.md
fourmolu.cabal

Blocked by https://github.com/fourmolu/fourmolu/pull/225

Release 0.8.1

---

README.md

Sorry, I'm a pedant. There's a lot of room for bikeshedding here.

Various minor style and grammar improvements to config options descriptions

---

changelog.d/promoted-space.md
data/examples/declaration/type/promotion-1-four-out.hs
data/examples/declaration/type/promotion-1-out.hs
data/examples/fourmolu/type-app-promoted-four-out.hs
data/examples/fourmolu/type-app-promoted-out.hs
data/examples/fourmolu/type-app-promoted.hs
src/Ormolu/Printer/Meat/Type.hs

Remove extra space in promoted types

---

changelog.d/module-warning-export.md
data/examples/module-header/warning-pragma-list-multiline-four-out.hs
data/examples/module-header/warning-pragma-multiline-four-out.hs
data/examples/module-header/warning-pragma-singleton-list-four-out.hs
src/Ormolu/Printer/Meat/ImportExport.hs
src/Ormolu/Printer/Meat/Module.hs

Trying to align closer to what Ormolu does here, which should also help with #167 
Blocks #245

Improve formatting of export list with module warning

---

changelog.d/respectful-module-where.md
data/examples/module-header/multiline-with-comments-four-out.hs
data/examples/module-header/named-section-four-out.hs
data/examples/module-header/warning-pragma-list-multiline-four-out.hs
data/examples/module-header/warning-pragma-multiline-four-out.hs
data/examples/other/empty-haddock-four-out.hs
data/fourmolu/import-export/output-ImportExportDiffFriendly.hs
data/fourmolu/respectful-module-where/input-multi.hs
data/fourmolu/respectful-module-where/output-respectful=False-ImportExportDiffFriendly.hs
data/fourmolu/respectful-module-where/output-respectful=False-ImportExportLeading.hs
data/fourmolu/respectful-module-where/output-respectful=False-ImportExportTrailing.hs
data/fourmolu/respectful-module-where/output-respectful=True-ImportExportDiffFriendly.hs
data/fourmolu/respectful-module-where/output-respectful=True-ImportExportLeading.hs
data/fourmolu/respectful-module-where/output-respectful=True-ImportExportTrailing.hs
src/Ormolu/Printer/Meat/Module.hs
tests/Ormolu/Config/PrinterOptsSpec.hs

Resolves https://github.com/fourmolu/fourmolu/issues/167
Blocked by #244

Respect "respectful" for where keyword in module header

---

fourmolu.cabal

Noticed these were wrong on Hackage today

Correct homepage/issue links

---

changelog.d/unicode.md
data/fourmolu/unicode-syntax/input.hs
data/fourmolu/unicode-syntax/output-UnicodeAlways.hs
data/fourmolu/unicode-syntax/output-UnicodeDetect.hs
data/fourmolu/unicode-syntax/output-UnicodeNever.hs
src/Ormolu/Printer/Combinators.hs
src/Ormolu/Printer/Meat/Declaration/Class.hs
src/Ormolu/Printer/Meat/Declaration/Data.hs
src/Ormolu/Printer/Meat/Declaration/Signature.hs
src/Ormolu/Printer/Meat/Declaration/TypeFamily.hs
src/Ormolu/Printer/Meat/Declaration/Value.hs
src/Ormolu/Printer/Meat/Type.hs

Unicode fixes

---

CHANGELOG.md
changelog.d/let-style.md
data/fourmolu/let-style/input.hs
data/fourmolu/let-style/output-LetAuto-InLeftAlign-indent=2.hs
data/fourmolu/let-style/output-LetAuto-InLeftAlign-indent=4.hs
data/fourmolu/let-style/output-LetAuto-InRightAlign-indent=2.hs
data/fourmolu/let-style/output-LetAuto-InRightAlign-indent=4.hs
data/fourmolu/let-style/output-LetInline-InLeftAlign-indent=2.hs
data/fourmolu/let-style/output-LetInline-InLeftAlign-indent=4.hs
data/fourmolu/let-style/output-LetInline-InRightAlign-indent=2.hs
data/fourmolu/let-style/output-LetInline-InRightAlign-indent=4.hs
data/fourmolu/let-style/output-LetMixed-InLeftAlign-indent=2.hs
data/fourmolu/let-style/output-LetMixed-InLeftAlign-indent=4.hs
data/fourmolu/let-style/output-LetMixed-InRightAlign-indent=2.hs
data/fourmolu/let-style/output-LetMixed-InRightAlign-indent=4.hs
data/fourmolu/let-style/output-LetNewline-InLeftAlign-indent=2.hs
data/fourmolu/let-style/output-LetNewline-InLeftAlign-indent=4.hs
data/fourmolu/let-style/output-LetNewline-InRightAlign-indent=2.hs
data/fourmolu/let-style/output-LetNewline-InRightAlign-indent=4.hs
src/Ormolu/Printer/Meat/Declaration/Value.hs

let-style improvements

---

README.md

Update docs for unicode

---

changelog.d/comments.md
data/fourmolu/haddock-style/input.hs
data/fourmolu/haddock-style/output-HaddockMultiLine-module=HaddockMultiLine.hs
data/fourmolu/haddock-style/output-HaddockMultiLine-module=HaddockMultiLineCompact.hs
data/fourmolu/haddock-style/output-HaddockMultiLine-module=HaddockSingleLine.hs
data/fourmolu/haddock-style/output-HaddockMultiLine.hs
data/fourmolu/haddock-style/output-HaddockMultiLineCompact-module=HaddockMultiLine.hs
data/fourmolu/haddock-style/output-HaddockMultiLineCompact-module=HaddockMultiLineCompact.hs
data/fourmolu/haddock-style/output-HaddockMultiLineCompact-module=HaddockSingleLine.hs
data/fourmolu/haddock-style/output-HaddockMultiLineCompact.hs
data/fourmolu/haddock-style/output-HaddockSingleLine-module=HaddockMultiLine.hs
data/fourmolu/haddock-style/output-HaddockSingleLine-module=HaddockMultiLineCompact.hs
data/fourmolu/haddock-style/output-HaddockSingleLine-module=HaddockSingleLine.hs
data/fourmolu/haddock-style/output-HaddockSingleLine.hs
src/Ormolu/Diff/ParseResult.hs
src/Ormolu/Printer/Meat/Common.hs
src/Ormolu/Utils.hs

Fix comments

---

.github/workflows/ci.yml
.github/workflows/pr-review-comment.yml
.github/workflows/release.yml

This format reduces diffs when changing the first line of a step, e.g.
```diff
-  - run: foo
+  - name: Do foo
+    run: foo
```
vs
```diff
-
+    name: Do foo
run: foo
```
It also helps to visually separate each step

Reformat Github actions files

---

data/fourmolu/let-style/output-LetAuto-InNoSpace-indent=2.hs
data/fourmolu/let-style/output-LetAuto-InNoSpace-indent=4.hs
data/fourmolu/let-style/output-LetInline-InNoSpace-indent=2.hs
data/fourmolu/let-style/output-LetInline-InNoSpace-indent=4.hs
data/fourmolu/let-style/output-LetMixed-InNoSpace-indent=2.hs
data/fourmolu/let-style/output-LetMixed-InNoSpace-indent=4.hs
data/fourmolu/let-style/output-LetNewline-InNoSpace-indent=2.hs
data/fourmolu/let-style/output-LetNewline-InNoSpace-indent=4.hs

#291 added a test case and #293 updated the input, and I forgot to rerun tests

Regenerate outputs for InNoSpace

---

.github/workflows/ci.yml
app/Main.hs

Ormolu changed this in 0.5.3.0, but I forgot to update this in #293

Fix git commit hash in binary

---

config/FourmoluConfig/ConfigData.hs
config/FourmoluConfig/GenerateUtils.hs
web/site/fourmolu-web.cabal
web/site/site.hs
web/site/static/demo.js

Resolves #317 
@georgefst Can't test right now because of #318. Should hopefully work as-is, but don't know for sure. If you can get that working, would be great if you can test this change with the `data/fourmolu/column-limit/input.hs` text + changing the `column-limit` input in the demo

Fix column-limit input

---

.github/workflows/web.yml
web/fourmolu-wasm/cabal.project
web/site/pages/config/column-limit.md
web/site/pages/index.md
web/site/static/demo.css
web/site/static/demo.js

Changes:
* It's easy for the program options to get lost in the sea of formatting options, which I suspect is the source of the confusion in #333
* Make the idempotence note more clear in the `column-limits` docs
* Show a warning when `column-limit` and `check-idempotence` are both set
---
---
---

Website improvements

---

fourmolu.cabal
src/Ormolu/Config.hs
tests/Ormolu/CabalInfoSpec.hs
tests/Ormolu/ConfigSpec.hs

Fix multiple reexports for same module

---

changelog.d/quantified-constraints-parents.md
data/fourmolu/single-constraint-parens/input.hs
data/fourmolu/single-constraint-parens/output-ConstraintAlways.hs
data/fourmolu/single-constraint-parens/output-ConstraintAuto.hs
data/fourmolu/single-constraint-parens/output-ConstraintNever.hs
src/Ormolu/Parser.hs

Fix `single-constraint-parens: never` with QuantifiedConstraints

---

changelog.d/single-export-leading.md
data/fourmolu/import-export/input-multi.hs
data/fourmolu/import-export/output-ImportExportDiffFriendly.hs
data/fourmolu/import-export/output-ImportExportLeading.hs
data/fourmolu/import-export/output-ImportExportTrailing.hs
src/Ormolu/Printer/Meat/Declaration/Value.hs
src/Ormolu/Printer/Meat/ImportExport.hs
src/Ormolu/Utils.hs
tests/Ormolu/Config/PrinterOptsSpec.hs

Fix single documented export with `import-export-style: leading`

---

README.md

Adds the `-P` flag to `xargs` to running fourmolu in parallel.

Suggest parallelism

---

.github/workflows/web.yml
web/fourmolu-wasm/cabal.project
web/site/pages/index.md
web/site/static/demo.css
web/site/static/demo.js

Add button to copy config in web app

---

.gitattributes
.github/workflows/web.yml
app/Main.hs
src/Ormolu.hs
src/Ormolu/Config.hs
tests/Ormolu/PrinterSpec.hs
web/fourmolu-wasm/cabal.project
web/fourmolu-wasm/src/Main.hs
web/site/site.hs
web/site/static/style.css
web/site/templates/default.html

Some repo cleanup + refactoring broken out from #364

Miscellaneous clean up + refactor

---

app/Main.hs

Make the config display with `--debug` nicer. See https://github.com/tweag/ormolu/pull/1045

Update debug logs

---

changelog.d/nested-constraint.md
data/fourmolu/single-constraint-parens/input.hs
data/fourmolu/single-constraint-parens/output-ConstraintAlways.hs
data/fourmolu/single-constraint-parens/output-ConstraintAuto.hs
data/fourmolu/single-constraint-parens/output-ConstraintNever.hs
src/Ormolu/Parser.hs

Fix single-constraint-parens for nested constraint

---

app/Main.hs
changelog.d/add-config-file.md
fourmolu.cabal
src/Ormolu.hs
src/Ormolu/Config.hs
tests/Ormolu/CabalInfoSpec.hs
tests/Ormolu/Integration/CLISpec.hs
tests/Ormolu/Integration/Utils.hs
tests/Ormolu/PrinterSpec.hs

Add --config CLI flag

---

DEVELOPER.md
app/Main.hs
fourmolu.cabal

Resolves #31
Here's the before:
Here's the after (terminal size = 100):

Update help text column widths

---

changelog.d/multiline-comments-indented.md
data/examples/declaration/data/infix-haddocks-four-out.hs
data/examples/declaration/data/operators-four-out.hs
data/examples/declaration/data/single-constructor-with-haddock-four-out.hs
data/examples/fourmolu/multiline-haddocks-four-out.hs
data/examples/import/docstrings-after-exports-four-out.hs
data/fourmolu/import-export/output-ImportExportDiffFriendly.hs
data/fourmolu/import-export/output-ImportExportLeading.hs
data/fourmolu/import-export/output-ImportExportTrailing.hs
src/Ormolu/Diff/ParseResult.hs
src/Ormolu/Printer/Combinators.hs
src/Ormolu/Printer/Internal.hs
src/Ormolu/Printer/Meat/Common.hs

Allow multiline comments in indented contexts

---

data/fourmolu/single-constraint-parens/input.hs
data/fourmolu/single-constraint-parens/output-ConstraintAlways.hs
data/fourmolu/single-constraint-parens/output-ConstraintAuto.hs
data/fourmolu/single-constraint-parens/output-ConstraintNever.hs
src/Ormolu/Parser.hs

Fix implicit params with single-constraint-parens

---

changelog.d/sort-constraints-data-con.md
data/fourmolu/sort-constraints/input.hs
data/fourmolu/sort-constraints/output-False.hs
data/fourmolu/sort-constraints/output-True.hs
src/Ormolu/Diff/ParseResult.hs

Fix AST error with sort-constraints

---

.github/workflows/ci.yml

Strip prod binaries
